### ISSUE TITLE
关于 ToFree 问题的咨询

### ISSUE THREAD

**Issue by wenfangdu** [CorrectRoadH/CorrectRoadH.github.io#13]
您好，请问您有 TG 账号嘛，关于 ToFree 有问题想咨询一下
P.S. 发送后可以将此 issue 删除

**Comment by CorrectRoadH** [comment]
> 您好，请问您有 TG 账号嘛，关于 ToFree 有问题想咨询一下 P.S. 发送后可以将此 issue 删除

[@testbindhdjd](http://tg.me/testbindhdjd)

**Comment by wenfangdu** [comment]
收到
